package com.retailer.rewards.entity;

import jakarta.persistence.*;
import java.util.List;

/**
 * Entity class representing a Customer in the retailer system.
 *
 * Each Customer has a unique ID, a name, and a list of associated transactions.
 * The relationship between Customer and Transaction is one-to-many.
 */

@Entity
public class Customer {
    /**
     * Primary key for Customer entity.
     * Auto-generated by the persistence provider.
     */
    @Id
    @GeneratedValue
    private Long id;
    /**
     * Name of the customer.
     */
    private String name;
    /**
     * List of transactions associated with this customer.
     * Cascade type ALL to propagate changes and orphanRemoval enabled.
     */
    @OneToMany(mappedBy = "customer", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Transaction> transactions;

    public Customer() {}

    public Customer(String name) {
        this.name = name;
    }

    // Getters and Setters
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public List<Transaction> getTransactions() { return transactions; }
    public void setTransactions(List<Transaction> transactions) { this.transactions = transactions; }
}
